export const QUERY_KEYS = {

    AUTH: {
        USER_INFO: "USER_INFO",
    },
    USER: {
        LIST_AGENT_NOTIFY: "LIST_AGENT_NOTIFY",
        LIST_USER_IN_COMPANY_OWNER: "LIST_USER_IN_COMPANY_OWNER",
        LIST_BOOKING_REQUEST: "LIST_BOOKING_REQUEST",
        LIST_DETAIL_BOOKING_REQUEST: "LIST_DETAIL_BOOKING_REQUEST",
        LIST_AGENT_REQUEST: "LIST_AGENT_REQUEST",
        LIST_REPORT_PAYABLE_BOOKING_ITEM_BY_AGENT: "LIST_REPORT_PAYABLE_BOOKING_ITEM_BY_AGENT",
        LIST_REPORT_COMMISSION_BY_AGENT_HOST: "LIST_REPORT_COMMISSION_BY_AGENT_HOST",
        LIST_PAID_BOOKING_ITEM: "LIST_PAID_BOOKING_ITEM",
        LIST_COMPANY_OWNER: "LIST_COMPANY_OWNER",
        LIST_TOUR_CUSTOMIZED: "LIST_TOUR_CUSTOMIZED",
        LIST_SERVICE_TOUR_CUSTOMIZED: "LIST_SERVICE_TOUR_CUSTOMIZED",
        LIST_TOUR_CUSTOMIZED_INEX: "LIST_TOUR_CUSTOMIZED_INEX",
        LIST_TOTAL_PRICE_FOR_TOUR_CUSTOM: "LIST_TOTAL_PRICE_FOR_TOUR_CUSTOM",
        LIST_COMPANY_BANK_ACCOUNT: "LIST_COMPANY_BANK_ACCOUNT",
        LIST_SALE_REQUEST: "LIST_SALE_REQUEST",
        LIST_AGENT_FOR_GROUP: "LIST_AGENT_FOR_GROUP",
        LIST_REPORT_RECEIV_ABLE_BY_AGENT: "LIST_REPORT_RECEIV_ABLE_BY_AGENT",
        LIST_AGENT_HOST_SERVICE_ITEM: "LIST_AGENT_HOST_SERVICE_ITEM",
        LIST_PAYABLE_BOOKING: "LIST_PAYABLE_BOOKING",
        LIST_PAID_BOOKING: "LIST_PAID_BOOKING",
        LIST_REQUEST_MESSAGE: "LIST_REQUEST_MESSAGE",
        LIST_SERVICE_ITEM_BY_SALE_REQ: "LIST_SERVICE_ITEM_BY_SALE_REQ",
        LIST_BOOKING: "LIST_BOOKING",
        LIST_HELPER_FILE_BY_SHOW: "LIST_HELPER_FILE_BY_SHOW",
        LIST_CART: "LIST_CART",
        LIST_OVERVIEW_TOUR_CUSTOMIZE: "LIST_OVERVIEW_TOUR_CUSTOMIZE",
    },
    TOUR:
    {
        LIST_TOUR: "LIST_TOUR",
        DETAIL_TOUR: "DETAIL_TOUR",
        LIST_TOUR_PUBLISH: "LIST_TOUR_PUBLISH",
        LIST_TOUR_DAY: "LIST_TOUR_DAY",
        LIST_SEARCH_TOUR: "LIST_SEARCH_TOUR",
        LIST_PARTNER: "LIST_PARTNER",
        LIST_TOUR_SERIES: "LIST_TOUR_SERIES",
        LIST_TOUR_CUSTOMIZE_DETAIL: "LIST_TOUR_CUSTOMIZE_DETAIL",
        LIST_OVERVIEW_TOUR_CUSTOM: "LIST_OVERVIEW_TOUR_CUSTOM"
    },
    TOUR_CUSTOMER:
    {
        LIST_TOUR_CUSTOMER: "LIST_TOUR_CUSTOMER",
        LIST_SUP_MAP_PRICE: "LIST_SUP_MAP_PRICE",
        LIST_TOUR_PUBLISH: "LIST_TOUR_PUBLISH",
    },
    HOTEL: {
        LIST_HOTEL: "LIST_HOTEL",
        LIST_ITEM_BY_AGENT: "LIST_ITEM_BY_AGENT",
        LIST_SEARCH_HOTEL: "LIST_SEARCH_HOTEL",
        LIST_SEARCH_DES_HOTEL: "LIST_SEARCH_DES_HOTEL"
    },
    BOAT: {
        LIST_BOAT: "LIST_BOAT",
        LIST_IMAGE: "LIST_IMAGE",
        LIST_MAPPING_PRICE: "LIST_MAPPING_PRICE",
    },
    COMPANY_OWNER: {
        LIST_COMPANY_OWNER: "LIST_COMPANY_OWNER",
        LIST_COMPANY_DES_DAY: "LIST_COMPANY_DES_DAY",
    },
    VEHICLE: {
        LIST_VEHICLE: "LIST_VEHICLE",
        DETAI_VEHICLE: "DETAIL_VEHICLE",
        LIST_MAPPING_PRICE: "LIST_MAPPING_PRICE",
    },
    FLIGHT: {
        LIST_FLIGHT: "LIST_FLIGHT",
        DETAIL_FLIGHT: "DETAIL_FLIGHT",
        LIST_MAPPING_PRICE: "LIST_MAPPING_PRICE",
    },
    RESTAURANT: {
        LIST_RESTAURANT: "LIST_RESTAURANT",
        DETAIL_RESTAURANT: "DETAIL_RESTAURANT",
        LIST_MAPPING_PRICE: "LIST_MAPPING_PRICE",
        LIST_IMAGE: "LIST_IMAGE",

    },
    GUIDE_FEE: {
        LIST_GUIDE_FEE: "LIST_GUIDE_FEE",
        DETAIL_GUIDE_FEE: "DETAIL_GUIDE_FEE",
        LIST_MAPPING_PRICE: "LIST_MAPPING_PRICE",
    },
    CART: {
        LIST_CART: "LIST_CART",

    },
    MENU: {
        LIST_MENU: "LIST_MENU",
    },
    VOUCHER: {
        LIST_VOUCHER: "LIST_VOUCHER",
    },
    MEDIA: {
        LIST_MEDIA: "LIST_MEDIA"
    },
    BOOKING: {
        LIST_PRICE: "LIST_PRICE"
    },
};
